@startuml
'https://plantuml.com/sequence-diagram

interface Board{
    - positions: Position[]

}

class Position{
    - verticalPosition: String
    - horizontalPosition: Integer
    - piece: Piece

}

Piece --> Color
interface Piece{
    - color: Color
    - movementValidation: MovementValidation
}

enum Color{
    - White
    - Black
}

class Game{
    - board: Board
    - victoryValidation: VictoryValidation
    - checkValidation: CheckValidation
    - surrenderValidation: SurrenderValidation
    - player1Pieces: Piece[]
    - player2Pieces: Piece[]
    - rules: RuleSet
    - turn: boolean
    + movePiece(piece: Piece, board: Board)

}

interface victoryValidation{}

interface checkValidation{}

interface surrenderValidation{}

interface movementValidation{}

Pawn ..|> Piece
class Pawn{
    - color: Color
    - movementValidation: MovementValidation
}

Knight ..|> Piece
class Knight{
    - color: Color
    - movementValidation: MovementValidation
}

Bishop ..|> Piece
class Bishop{
    - color: Color
    - movementValidation: MovementValidation
}

Rook ..|> Piece
class Rook{
    - color: Color
    - movementValidation: MovementValidation
}

Queen ..|> Piece
class Queen{
    - color: Color
    - movementValidation: MovementValidation
}

King ..|> Piece
class King{
    - color: Color
    - movementValidation: MovementValidation
}



/'
    --|> herencia
    *-- composición
    o-- agregación
    --> asosiación
    ..> dependencia
    <|.. realización/implementación
'/
@enduml